apiVersion: v1
kind: Pod
metadata:
  name: private-reg
  namespace: ms-namespace
spec:
  containers:
  - name: private-reg-container
    image: myimage1
    imagePullPolicy: Never
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: regcred